# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.163.com
    username: 18329503441@163.com
    password: UGbq6K3fLH8xmKeW
  rabbitmq:
    addresses: 192.168.65.131
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/campus_forum
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: "abcdefghijklmn"
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: "*"
      credentials: false
      methods: "*"
  minio:
    endpoint: http://192.168.65.128:9000
    username: minio
    password: password
  weather:
    key: dbd7383a6fce44f48313afd8ba1d8843
    apihost: nu3qqpjw8a.re.qweatherapi.com
  ai:
    deepseek:
      api-key: 'agent-8a2e843d04f11f91b38c9bf1e59afc71'
      base-url: 'http://localhost:8099/chat/api/019bc72a-d237-7c10-9ddf-56a303eb4537'


